### ISSUE TITLE
Some issues regarding signal classification

### ISSUE THREAD

**Issue by zzz135790** [koc-lab/TrainableFrFT#2]
Now there is a signal classification task，the input signal is a one-dimensional real number signal, that is, a one-dimensional sequence. I use trainable FRFT to process the input signal, and then use CNN and linear layers to classify the processed data. Here, the CNN input is dual channel, and the transformed real and imaginary parts are processed separately. May I ask why the effect is worse than using only CNN and linear layers, and where is the error? Thank you for your answer。By the way, the code I referenced is  [GitHub page of torch-frft](https://github.com/tunakasif/torch-frft)，only added a CNN and linear layer at the end

**Comment by kocemir** [comment]
From my previous time series and image processing experiences with these transformations, I saw that taking magnitude response of the transformed data works better than seperating to different channels or taking  only real/imaginary parts. I do not think there is a mistake or error, but in your design, it might not work well, it may require more search for hyperparameter sthat work well with your and baseline method. 

It is also worth to indicate that applying these transformations to the very beginning of the networks ( like input and first layers ) may bring about the problem for parameter update of frft due to vanishing gradient. The information flow up to first layers from the classification block may not be sufficient. In this case, it might be good idea to take inverse of transformation just a few layer prior to classification layer.

**Comment by zzz135790** [comment]
Thank you for your answer. I made some mistakes and conducted another experiment, which proved that your method is indeed effective. I have another question. I only used FRFT to transform the input into the time domain and then input it into CNN and classifier for classification without performing inverse transformation. Is inverse transformation necessary？

**Comment by kocemir** [comment]
As I stated in my previous answer, if you apply it to first layer, I think it would be nice to apply inverse transformation. However, if you use it in further layers, even if you do not invert the transform, it probably still works fine.
